import { COTIZACION, LINEA } from "@/test/v2next/shellFixtures";
import type { V2Illustration, V2LaborPage, V2Technique, V2Worker } from "@/types/quoterV2Labor";
import type { V2QuotationProductsPage } from "@/types/quoterV2Materials";
import type { V2ProcessPage } from "@/types/quoterV2Processes";
import type { V2Quotation } from "@/types/quoterV2";

export const COTIZACION_TRABAJO: V2Quotation = {
  ...COTIZACION,
  space_service_cost_per_day: "140.000000",
};

export const COTIZACION_TRABAJO_USD: V2Quotation = {
  ...COTIZACION_TRABAJO,
  currency_code: "USD",
  currency_symbol: "US$",
  exchange_rate: "3.750000",
};

export const PRODUCTOS_TRABAJO: V2QuotationProductsPage = {
  materials_cost: "18.000000",
  items: [
    {
      ...LINEA,
      id: 11,
      product_name: "Plato palta",
      quantity: 20,
    },
    {
      ...LINEA,
      id: 12,
      product_name: "Taza luna",
      quantity: 6,
    },
  ],
};

export const TRABAJADORES_TRABAJO: { items: V2Worker[] } = {
  items: [
    {
      id: 1,
      name: "Celso",
      worker_type: "INTERNAL",
      active: true,
      daily_rate: "120.000000",
      workday_hours: null,
      effective_workday_hours: "8.000000",
      hourly_rate: "15.000000000000",
      notes: null,
      version: 1,
      technique_ids: [3],
    },
    {
      id: 2,
      name: "Refuerzo externo",
      worker_type: "EXTERNAL",
      active: true,
      daily_rate: "160.000000",
      workday_hours: null,
      effective_workday_hours: "8.000000",
      hourly_rate: "20.000000000000",
      notes: null,
      version: 1,
      technique_ids: [3, 4],
    },
    {
      id: 3,
      name: "Pintora",
      worker_type: "EXTERNAL",
      active: true,
      daily_rate: "180.000000",
      workday_hours: null,
      effective_workday_hours: "8.000000",
      hourly_rate: "22.500000000000",
      notes: null,
      version: 1,
      technique_ids: [5],
    },
  ],
};

export const TECNICAS_TRABAJO: { items: V2Technique[] } = {
  items: [
    {
      id: 3,
      code: "vidriado",
      name: "Vidriado",
      active: true,
      default_capacity_per_workday: "50.000000",
      unit: "piezas",
      requires_glaze: true,
      manual_hours: false,
      units_per_hour: "6.250000000000",
      notes: null,
      version: 1,
    },
    {
      id: 4,
      code: "pulido",
      name: "Pulido",
      active: true,
      default_capacity_per_workday: "1.000000",
      unit: "piezas",
      requires_glaze: false,
      manual_hours: true,
      units_per_hour: "0.125000000000",
      notes: null,
      version: 1,
    },
    {
      id: 5,
      code: "aplique",
      name: "Aplique",
      active: true,
      default_capacity_per_workday: "24.000000",
      unit: "piezas",
      requires_glaze: false,
      manual_hours: false,
      units_per_hour: "3.000000000000",
      notes: null,
      version: 1,
    },
  ],
};

export const PROCESOS_TRABAJO: V2ProcessPage = {
  warnings: ["V2_PROCESS_PRODUCT_WITHOUT_TECHNIQUES"],
  items: [
    {
      id: 501,
      v2_quotation_product_id: 11,
      product_name: "Plato palta",
      technique_id: 3,
      technique_name: "Vidriado",
      technique_unit: "piezas",
      technique_active: true,
      standard_capacity: "50.000000",
      manual_hours: false,
      origin: "PRODUCT",
      quantity: "20.000000",
      quantity_overridden: false,
      calculated_hours: "3.200000",
      labor_id: 601,
      worker_id: 1,
      worker_name: "Celso",
      final_hours: "4.000000",
      labor_cost: "0.000000",
      warnings: ["V2_PROCESS_TECHNIQUE_INACTIVE"],
    },
    {
      id: 502,
      v2_quotation_product_id: 11,
      product_name: "Plato palta",
      technique_id: 4,
      technique_name: "Pulido",
      technique_unit: "piezas",
      technique_active: true,
      standard_capacity: "1.000000",
      manual_hours: true,
      origin: "MANUAL",
      quantity: "20.000000",
      quantity_overridden: true,
      calculated_hours: null,
      labor_id: null,
      worker_id: null,
      worker_name: null,
      final_hours: null,
      labor_cost: null,
      warnings: [],
    },
  ],
};

export const MANO_DE_OBRA_TRABAJO: V2LaborPage & { warnings: string[] } = {
  items: [
    {
      id: 601,
      sort_order: 0,
      v2_quotation_product_id: 11,
      worker_id: 1,
      worker_name: "Celso",
      worker_type: "INTERNAL",
      daily_rate: "120.000000",
      workday_hours: "8.000000",
      hourly_rate: "15.000000000000",
      rate_overridden: false,
      technique_id: 3,
      technique_name: "Vidriado",
      technique_unit: "piezas",
      standard_capacity: "50.000000",
      quantity: "20.000000",
      calculated_hours: "3.200000",
      final_hours: "4.000000",
      hours_overridden: true,
      is_additional_personnel: false,
      labor_cost: "0.000000",
      warnings: ["V2_LABOR_WORKDAY_EXCEEDED", "V2_AVISO_NUEVO"],
    },
    {
      id: 602,
      sort_order: 1,
      v2_quotation_product_id: null,
      worker_id: 2,
      worker_name: "Refuerzo externo",
      worker_type: "EXTERNAL",
      daily_rate: "160.000000",
      workday_hours: "8.000000",
      hourly_rate: "20.000000000000",
      rate_overridden: true,
      technique_id: 4,
      technique_name: "Pulido",
      technique_unit: "piezas",
      standard_capacity: "1.000000",
      quantity: "10.000000",
      calculated_hours: "10.000000",
      final_hours: "10.000000",
      hours_overridden: true,
      is_additional_personnel: true,
      labor_cost: "200.000000",
      warnings: [],
    },
  ],
  labor_cost: "200.000000",
  workday_load: [
    {
      worker_id: 1,
      worker_name: "Celso",
      workday_hours: "8.000000",
      assigned_hours: "4.000000",
      exceeds_workday: false,
      minimum_days: 1,
    },
    {
      worker_id: 2,
      worker_name: "Refuerzo externo",
      workday_hours: "8.000000",
      assigned_hours: "10.000000",
      exceeds_workday: true,
      minimum_days: 2,
    },
  ],
  suggested_work_days: 2,
  effective_work_days: null,
  warnings: ["V2_LABOR_WORKER_UNAVAILABLE"],
};

export const ILUSTRACION_TRABAJO: V2Illustration = {
  enabled: true,
  quantity: "3.000000",
  notes: null,
  daily_rate: "110.000000",
  workday_hours: "8.000000",
  capacity_per_workday: "50.000000",
  hourly_rate: "13.750000000000",
  hours: "0.480000",
  cost: "6.600000",
  lines: [
    {
      line_id: 11,
      product_name: "Plato palta",
      quantity: "5.000000",
      hours: "0.800000",
      cost: "11.000000",
    },
    {
      line_id: 12,
      product_name: "Taza luna",
      quantity: "0.000000",
      hours: "0.000000",
      cost: "0.000000",
    },
  ],
  total_hours: "1.280000",
  total_cost: "17.600000",
};
