import type { V2QuotationProduct } from "@/types/quoterV2Materials";

export const CUSTOM_PIECE: V2QuotationProduct = {
  id: 1,
  sort_order: 1,
  product_id: null,
  product_name: "Taza personalizada",
  quantity: 2,
  production_time_per_unit_minutes: null,
  mold_count: 1,
  cycles: 2,
  line_active_minutes: null,
  length_cm: "10.0",
  width_cm: "8.0",
  height_cm: "10.0",
  unit_volume_cm3: "800.0",
  total_volume_cm3: "1600.0",
  firing_occupancy_percent: "2.50",
  firing_volume_share_percent: "100.00",
  firing_commercial_cost: "0",
  firing_gas_cost: "0",
  client_observation: "Con asa grande",
  warnings: [],
  body_material_id: null,
  body_material_name: null,
  body_unit_weight: null,
  body_uom: null,
  body_cost_per_unit: null,
  body_cost_is_override: false,
  body_total_weight: "0",
  body_cost: "0",
  requires_glaze: false,
  glaze_material_id: null,
  glaze_material_name: null,
  glaze_is_reference: false,
  glaze_cost_per_unit: null,
  glaze_cost_is_override: false,
  glaze_percent: null,
  glaze_ml_per_gram: null,
  glaze_conversion_is_fallback: false,
  glaze_total_weight: "0",
  glaze_volume_ml: "0",
  glaze_cost: "0",
  materials_cost: "0",
};

export const CATALOG_PIECE: V2QuotationProduct = {
  id: 2,
  sort_order: 2,
  product_id: 101,
  product_name: "Plato hondo",
  quantity: 1,
  production_time_per_unit_minutes: null,
  mold_count: 1,
  cycles: 1,
  line_active_minutes: null,
  length_cm: "20.0",
  width_cm: "20.0",
  height_cm: "5.0",
  unit_volume_cm3: "2000.0",
  total_volume_cm3: "2000.0",
  firing_occupancy_percent: "3.10",
  firing_volume_share_percent: "50.00",
  firing_commercial_cost: "0",
  firing_gas_cost: "0",
  client_observation: null,
  warnings: ["NO_BODY"],
  body_material_id: null,
  body_material_name: null,
  body_unit_weight: null,
  body_uom: null,
  body_cost_per_unit: null,
  body_cost_is_override: false,
  body_total_weight: "0",
  body_cost: "0",
  requires_glaze: false,
  glaze_material_id: null,
  glaze_material_name: null,
  glaze_is_reference: false,
  glaze_cost_per_unit: null,
  glaze_cost_is_override: false,
  glaze_percent: null,
  glaze_ml_per_gram: null,
  glaze_conversion_is_fallback: false,
  glaze_total_weight: "0",
  glaze_volume_ml: "0",
  glaze_cost: "0",
  materials_cost: "0",
};
